import { describe, expect, it } from 'vitest'
import { initialTicketTiers } from '../../src/data/officialContent'
import { parseContentSyncProposal, processContentSyncProposal, type ContentSyncProposal, type ContentSyncTransaction, type OfficialContentDocument, type OfficialContentType, type StoredContentProposal } from './contentSync'
import { createHash } from 'node:crypto'

class MemoryStore {
  documents=new Map<string,OfficialContentDocument>(); proposals=new Map<string,StoredContentProposal>(); states=new Map<string,string>(); audits:unknown[]=[]; histories:unknown[]=[]
  async runTransaction<T>(run:(transaction:ContentSyncTransaction)=>Promise<T>){ return run({getDocument:async(type,id)=>this.documents.get(`${type}:${id}`)??null,getProposal:async(id)=>this.proposals.get(id)??null,getLatestObservedAt:async(key)=>this.states.get(key)??null,setDocument:(type,value)=>{this.documents.set(`${type}:${value.id}`,structuredClone(value))},setProposal:(id,value)=>{this.proposals.set(id,value)},setState:(key,value)=>{this.states.set(key,String(value.latestObservedAt))},setAudit:(_id,value)=>{this.audits.push(value)},setHistory:(_type,_documentId,_id,value)=>{this.histories.push(value)}}) }
}
function proposal(document=structuredClone(initialTicketTiers[1]),id='content-proposal-1'):ContentSyncProposal { document.sourceObservedAt='2026-08-23T00:00:00.000Z'; return {proposalId:id,contentType:'TICKET_TIER',documentId:document.id,observedAt:document.sourceObservedAt,source:{url:document.sourceUrl,type:'OFFICIAL',publisher:'Tomorrowland'},document,evidence:{excerpt:'Tomorrowland Brasil 2027 Comfort Areas y precios oficiales publicados.',sourceHash:createHash('sha256').update('evidence').digest('hex'),kind:'CONFIRMATION'}} }
describe('official content sync',()=>{
  it('valida schema estricto y fuente oficial',()=>{ expect(parseContentSyncProposal(proposal()).documentId).toBe('comfort'); expect(()=>parseContentSyncProposal({...proposal(),extra:true})).toThrow(); const invalid=proposal(); invalid.source.url='https://tomorrowland.com.evil.example/'; expect(()=>parseContentSyncProposal(invalid)).toThrow() })
  it('dry-run crea sin escribir y real crea con auditoría e historial',async()=>{ const store=new MemoryStore(); const value=proposal(); expect((await processContentSyncProposal(store,value,{dryRun:true,now:()=>new Date('2026-08-23T12:00:00Z')})).result).toBe('CREATED'); expect(store.documents.size).toBe(0); expect((await processContentSyncProposal(store,value,{dryRun:false,now:()=>new Date('2026-08-23T12:00:00Z')})).result).toBe('CREATED'); expect(store.documents.size).toBe(1); expect(store.audits).toHaveLength(1); expect(store.histories).toHaveLength(1) })
  it('NO_CHANGE no crea historial e idempotencia no duplica',async()=>{ const store=new MemoryStore(); const value=proposal(); store.documents.set('TICKET_TIER:comfort',structuredClone(value.document)); const first=await processContentSyncProposal(store,value,{dryRun:false,now:()=>new Date('2026-08-23T12:00:00Z')}); expect(first.result).toBe('NO_CHANGE'); expect(store.histories).toHaveLength(0); expect((await processContentSyncProposal(store,value,{dryRun:false,now:()=>new Date('2026-08-23T12:00:00Z')})).result).toBe('ALREADY_PROCESSED'); expect(store.audits).toHaveLength(1) })
  it('rechaza conflicto, stale y regresión de precio oficial',async()=>{ const store=new MemoryStore(); const value=proposal(); store.documents.set('TICKET_TIER:comfort',structuredClone(value.document)); await processContentSyncProposal(store,value,{dryRun:false,now:()=>new Date('2026-08-23T12:00:00Z')}); const conflict=proposal(structuredClone(initialTicketTiers[1])); conflict.document.description='otro'; expect((await processContentSyncProposal(store,conflict,{dryRun:false,now:()=>new Date()})).rejectionCode).toBe('IDEMPOTENCY_CONFLICT'); const regression=proposal(structuredClone(initialTicketTiers[1]),'content-proposal-2'); regression.document.offerings[0].totalPrice=null; regression.document.offerings[0].priceType=null; expect((await processContentSyncProposal(store,regression,{dryRun:true,now:()=>new Date()})).rejectionCode).toBe('ANTI_REGRESSION') })
  it('mantiene colecciones administrativas privadas por diseño de store',()=>{ const type:OfficialContentType='IMPORTANT_INFORMATION'; expect(type).toBe('IMPORTANT_INFORMATION') })
})
