import { describe, expect, it } from 'vitest'
import { CONTENT_RESEARCH_SOURCES, processContentProposal, researchOfficialContent } from './tomorrowlandContentResearch'
import type { FetchedOfficialPage } from './tomorrowlandResearch'

const prices:Record<string,string>={ 'festival-tickets':'Full Madness Pass R$ 3.160 Full Madness Comfort Pass R$ 5.535 Full Madness N°1 Pass R$ 9.715', 'easy-tent-2p':'Easy Tent 2P R$ 7.609 Easy Tent 2P Comfort R$ 12.359 Easy Tent 2P N°1 R$ 20.719', 'spectacular-easy-tent-2p':'Spectacular Easy Tent 2P R$ 8.359 Spectacular Easy Tent 2P Comfort R$ 13.109 Spectacular Easy Tent 2P N°1 R$ 21.469', 'vida-nova-2p':'Vida Nova 2P R$ 7.009 Vida Nova 2P Comfort R$ 11.759 Vida Nova 2P N°1 R$ 20.119', 'global-journey-hotels':'Hotel Packages with an optional add-on for Comfort or N°1 access prices to be announced', 'how-to-order':'Subject to availability one Treasure Case every two Bracelets delivery fees' }
function pages():Record<string,FetchedOfficialPage>{ return Object.fromEntries(CONTENT_RESEARCH_SOURCES.map((source)=>[source.id,{url:source.url,fetchedAt:'2026-08-23T12:00:00Z',html:`<!doctype html><html><body>Tomorrowland Brasil 2027 ${prices[source.id]} ${source.id==='festival-tickets'?'Comfort Areas Welcome Drink 13:00 15:00 N°1 MainStage São Paulo Itu Home Delivery October 24 Treasure Case Festival Box Office':''}</body></html>`}])) }
describe('research de tiers e información',()=>{
  it('extrae Comfort, N°1, precios y Treasure Case de evidencia inequívoca',()=>{ const result=researchOfficialContent(pages()); expect(result.status).toBe('PROPOSAL_CREATED'); expect(result.proposals).toHaveLength(8); expect(result.proposals[0].evidence.sourceHash).toMatch(/^[a-f0-9]{64}$/) })
  it('usa hash para no reprocesar la misma evidencia',()=>{ const first=researchOfficialContent(pages()); expect(researchOfficialContent(pages(),first.hash).status).toBe('NO_SOURCE_CHANGE') })
  it('falla de forma conservadora ante evidencia ambigua o precio ausente',()=>{ const input=pages(); input['festival-tickets'].html='<!doctype html><html>Tomorrowland Brasil 2027</html>'; expect(researchOfficialContent(input).status).toBe('PARSE_FAILED') })
  it('no infiere modalidades Global Journey si la relación explícita desaparece',()=>{ const input=pages(); input['global-journey-hotels'].html='<!doctype html><html><body>Hotel Packages</body></html>'; expect(researchOfficialContent(input).status).toBe('PARSE_FAILED') })
  it('hace dry-run y solo escribe CREATED/UPDATED',async()=>{ const proposal=researchOfficialContent(pages()).proposals[0]; const calls:boolean[]=[]; const client={submit:async(_proposal:typeof proposal,dryRun:boolean)=>{calls.push(dryRun); return {proposalId:proposal.proposalId,documentId:proposal.documentId,result:'UPDATED' as const,changedFields:['benefits'],dryRun}}}; await processContentProposal(client,proposal,true); expect(calls).toEqual([true,false]) })
  it('no escribe ante NO_CHANGE o REJECTED',async()=>{ const proposal=researchOfficialContent(pages()).proposals[0]; for(const result of ['NO_CHANGE','REJECTED'] as const){const calls:boolean[]=[]; await processContentProposal({submit:async(_p,dryRun)=>{calls.push(dryRun);return {proposalId:proposal.proposalId,documentId:proposal.documentId,result,changedFields:[],dryRun}}},proposal,true); expect(calls).toEqual([true])} })
})
